{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: expense-api-migrations
  labels:
    {{- include "expense-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: expense-api-migrations
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: Never

      # IMPORTANT: reuse the same ServiceAccount that has Workload Identity
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "expense-api.serviceAccountName" .) }}

      containers:
        - name: migrator
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: KeyVault__Uri
              value: "{{ .Values.keyVault.uri }}"
            - name: AZURE_CLIENT_ID
              value: "{{ .Values.workloadIdentity.clientId }}"
{{- end }}