apiVersion: v1
kind: Secret
metadata:
  name: expense-api-secrets
  labels:
    {{- include "expense-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}