apiVersion: apps/v1
kind: Deployment
metadata:
  name: acr-pull-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acr-pull-test
  template:
    metadata:
      labels:
        app: acr-pull-test
    spec:
      containers:
        - name: api
          image: acrexptrackerhqdev01.azurecr.io/expense-api:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080